export default [
	{
		root: true,
		env: { browser: true, es2020: true },
		extends: [
			"eslint:recommended",
			"plugin:@typescript-eslint/recommended",
			"plugin:react-hooks/recommended",
			"plugin:storybook/recommended",
			"plugin:storybook/recommended",
		],
		parser: "@typescript-eslint/parser",
		parserOptions: { project: ["./tsconfig.json"] },
		ignorePatterns: ["dist", "eslint.config.js"],
		files: ["packages"],
		plugins: ["react-refresh", "detect-bad-words"],
		rules: {
			"react-refresh/only-export-components": ["warn", { allowConstantExport: true }],
			semi: ["warn", "always"],
			quotes: ["warn", "double"],
			"prefer-const": "warn",
			"no-dupe-else-if": "error",
			"no-await-in-loop": "warn",
			"no-unused-vars": "warn",
			"no-duplicate-imports": "error",
			"react-hooks/rules-of-hooks": "error",
			"react-hooks/use-memo-correctly": "warn",
			"detect-bad-words/in-code": "error",
			"detect-bad-words/in-comment": "error",
			// "no-empty-function": "error",
			// "react/require-default-props": "warn",
			// 'no-console': 'error',
		},
	},
];
