name: Publish

on:
    push:
        branches:
            - main
    release:
        types: [created]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Set up PNPM
              uses: pnpm/action-setup@v2
              with:
                  version: 8.x

            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 16.x
                  registry-url: https://npm.pkg.github.com/

            - name: Install dependencies
              run: pnpm install --frozen-lockfile

            - name: Lint
              run: pnpm run lint

            - name: Build project
              run: pnpm run build

            - name: Authenticate with npm registry
              run: echo "//registry.npmjs.org/:_authToken=\${{ secrets.NPM_TOKEN }}" > .npmrc

            - name: Create Release Pull Request or Publish
              id: changesets
              uses: changesets/action@v1
              with:
                  publish: pnpm changeset publish
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

    publish-gpr:
        needs: build
        runs-on: ubuntu-latest
        permissions:
            packages: write
            contents: read
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Set up PNPM
              uses: pnpm/action-setup@v2
              with:
                  version: 8.x

            - uses: actions/setup-node@v3
              with:
                  node-version: 16.x
                  registry-url: https://npm.pkg.github.com/

            - name: Authenticate with npm registry
              run: echo "//registry.npmjs.org/:_authToken=\${{ secrets.NPM_TOKEN }}" > .npmrc

            - run: pnpm install --frozen-lockfile
            - run: pnpm publish --no-git-checks
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
